### ISSUE TITLE
License 

### ISSUE THREAD

**Issue by ThorstenBux** [WebAR-rocks/WebAR.rocks.face#25]
Does the GPL license allow to use your software commercially without a monthly fee?

**Comment by xavierjs** [comment]
Hi @ThorstenBux 
The GPL license allows using this software for free, even commercially.

But then your commercial software has to comply with the GPL license (it should be licensed under GPL too), which is not acceptable for many companies who will prefer getting a commercial license instead of publishing their source code to comply with the GPL license constraints.

I found this good article explaining the pros of this dual licensing: https://blog.cerebralab.com/Dual_licensing_GPL_for_fame_and_profit
