### ISSUE TITLE
WEBCAM_UNAVAILABLE and cant start in development mode in react

### ISSUE THREAD

**Issue by bishalDores** [WebAR-rocks/WebAR.rocks.face#40]
hi @xavierjs  , i clone the project and according to the readme.md file i used the reactThreeFiberDemos to run in a react project but unfortunately in development mode it didnt run and also after build the project then it run but an error occurs . that is WBCAM_UNAVAILABLE .but my camera is still on. 
how to resolve this issue ?
this happened after running dist folder
![Capture](https://user-images.githubusercontent.com/36929343/234501642-0e6b8f19-bf5a-4fa8-bd7a-6c79f77d22e0.PNG)

![Capture2](https://user-images.githubusercontent.com/36929343/234501636-761b2879-50d9-4809-a6e7-9485ed2ec56a.PNG)

this happened after running in development mode
![Capture3](https://user-images.githubusercontent.com/36929343/234501882-12df018e-415f-4ae0-99c6-6e9b7370763b.PNG)
![Capture4](https://user-images.githubusercontent.com/36929343/234501888-6b8c457d-06d0-4b8d-b12c-109c1063ddfe.PNG)

**Comment by siam88** [comment]
I had the similar problem. i am also stuck in this situation

**Comment by xavierjs** [comment]
Hi @bishalDores you need to start the project with a HTTPS server, not an HTTP one (I see that you use 8080 port which is http). Mediastream API do not allow camera access for unsecured HTTP, except for localhost.

**Comment by xavierjs** [comment]
I also noticed that I forgot to push the package-lock.json file. Please remove `node_modules` directory, run `npm install` and `npm run start` again

**Comment by siam88** [comment]
hi @xavierjs . what's your opinion on running it locally? because it is showing **Compiled successfully** in the terminal but in the browser, I am getting **This site can’t be reached** how can I resolve this? Noted that while I am running it locally it is running on **https://0.0.0.0:8443/** but is it supposed to run on localhost? if I am not wrong please help

this is the screenshot while i am running it locally or from terminal 
![Capture](https://user-images.githubusercontent.com/29373770/234751753-3a353ad9-7dc2-48f8-b24f-c1512066002c.PNG)

this is the result page after running it on browser
![Capture2](https://user-images.githubusercontent.com/29373770/234751879-99473a0b-eaa9-4e33-ab61-ca1eb5ddcb92.PNG)

**Comment by xavierjs** [comment]
Hi @siam88 
the `localhost:8080` was a mistake in the README.
Since in the console it says that the server is listening on port 8443, but in the browser, you cannot reach it, then something blocks it.
It should be a firewall issue, or maybe you are using a proxy / VPN
